### ISSUE TITLE
dev에 삭제해야할 파일들이 같이 들어가있습니다..

### ISSUE THREAD

**Issue by zmtlzmtl** [PLMOW/Pinterest-BE#29]
comments.repository.js
comments.repository.spec.js

pins.route.js
comments.route.js

복수형이라 단수형으로 바꿨었는데 같이 저장된것같습니다!

**Comment by minenam** [comment]
pull 이 제대로 안 되서 생긴 것 같은데, 이 부분은 구현 완료되면 전체적으로 한꺼번에 수정할게요!
